name: test_pragma
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment: 
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  http: ^0.13.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.2.19

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  image: assets/splash/catbreeds.png
  android_12:
    image: assets/splash/catbreeds.png
    color: "#000000"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/splash/
